version: '3.1'
services:
  app:
    container_name: web-back
    image: web-back
    build: ./
    ports:
      - "8080:8080"
  postgresqldb:
    image: postgres
    ports:
      - "1199:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=film_db